theme: jekyll-theme-cayman

layout: page
title: "Welcome to WeBuildPC's"
permalink: /index.md

layout: page
title: "User Guide"
permalink: /user.md


layout: page
title: "Employee Guide"
permalink: /employee.md
